# docker-compose.override.yml
version: '3.7'
services:
    php:
        volumes:
            - ./app/:/var/www/html

    nginx:
        volumes:
            - ./app/public/:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - '${NGINX_PORT}:80'

    adminer:
        ports:
            - '${ADMINER_PORT}:8080'